plugin:
  inputs:
    libinput_command_input:
      show-keycodes: true

# hold:
#   2:
#     sendkey: "LEFTMETA"

swipe:
  3:
    left:
      command: "bspc desktop -f prev.occupied.local"
    right:
      command: "bspc desktop -f next.occupied.local"

threshold:
  swipe: 0.5