#! /bin/bash

external_monitor=$(xrandr --query | grep 'VGA-1')

if [[ "$external_monitor" == "VGA-1 connected"* ]]; then
  echo "Dual Monitor Detected."

  xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal
  xrandr --output VGA-1 --mode 1280x1024 --rotate left --left-of eDP-1
  
  bspc monitor eDP-1 -d I II III IV V
  bspc monitor VGA-1 -d VI VII VIII IX

  bspc monitor VGA-1 -s eDP-1
else
  echo "Single Monitor Detected."

  xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal
  xrandr --output VGA-1 --off

  bspc monitor eDP-1 -d I II III IV V VI VII VIII IX
fi
