#!/usr/bin/env sh

running=$(playerctl -l 2>&1 | grep 'chrome')

title=$(playerctl metadata title --player=chrome 2>&1)
artist=$(playerctl metadata artist --player=chrome 2>&1)

spotify=$(brotab list | grep 'https://open.spotify.com')
kitabsawti=$(brotab list | grep 'https://kitabsawti.com')

# Chrome Is Running
if [ -n "$running" ]; then

  # Kitab Sawti Is Running
  if [ -n "$kitabsawti" ] && [ -z "$artist" ]; then
    title="$(echo "$title" | sed -e "s/بجودة عالية. لا حاجة لـ//" -e "s/PDF بعد الآن — كتاب صوتي Kitab Sawti//")"
    icon=""
  
  # Spotify Is Running
  elif [ -n "$spotify" ]; then
    title="$(echo "$title")"
    icon="󰓇"
  fi

  # if title includes Arabic then reverse direction to RTL and fix the glyphs
  if [[ -n "$( echo "$title" | grep -o -P "\p{Arabic}" )" ]]; then
    alt="$icon"
    icon="$(ara.sh "$title")"
    title="$alt"
  fi

  if [[ "$1" == "title" ]]; then
    echo "$title"
  elif [[ "$1" == "icon" ]]; then
    echo "$icon"
  fi

elif [[ "$1" == "title" ]]; then
  echo "Hello, $USER."
fi