#! /bin/sh

bspc config border_width        0
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus true

###
bspc config external_rules_command ~/.bin/external_rules_1.sh
bspc subscribe node_remove | while read -r event
do
   external_rules_2.sh "$event"
done &
###

# setup monitor
dual_monitor &
