#! /bin/sh

bspc config border_width        0
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus true

bspc config external_rules_command ~/.bin/external_rule_pip.sh

bspc rule -a "Alacritty" state=pseudo_tiled follow=on

bspc rule -a "Authy Desktop" state=pseudo_tiled rectangle=400x680+0+0

bspc rule -a "Peek" state=floating rectangle=640x480+0+0

# setup monitor
dual_monitor
