#! /bin/sh

bspc config border_width        0
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a "Alacritty" state=pseudo_tiled follow=on

bspc rule -a "Code" state=pseudo_tiled rectangle=800x600+0+0

bspc rule -a "Authy Desktop" state=pseudo_tiled rectangle=400x680+0+0

bspc rule -a "Gnome-calculator" state=pseudo_tiled

bspc rule -a "Gcolor2" state=pseudo_tiled

# dual monitor detection and setup
dual_monitor

# set default wallpaper
wall.sh

# polybar
bar.sh &